framework:
    default_locale: "%locale%"
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - "%locale%"

jms_i18n_routing:
    default_locale: ua
    locales: [ua, ru]
    strategy: prefix_except_default